fix: update cost table format of quokka

diff --git a/qfusion-opt/Makefile b/qfusion-opt/Makefile
--- a/qfusion-opt/Makefile
+++ b/qfusion-opt/Makefile
@@ -9,18 +9,18 @@ MODE=3
 fusion: fusion.cpp
 	${CXX} ${CXXFLAGS} -o $@ $^
 
-fusion_ori: fusion_ori.cpp
-	${CXX} ${CXXFLAGS} -o $@ $^
+# fusion_ori: fusion_ori.cpp
+# 	${CXX} ${CXXFLAGS} -o $@ $^
 
 run: fusion
 	@for i in `seq 1 ${NUM}`; do \
 		./fusion ./circuit/${TEST} ./tmp/${TEST} 3 ${QUBIT} ${MODE}; \
 	done;
 
-check: fusion fusion_ori
-	@./fusion ./circuit/${TEST} ./tmp/${TEST} 3 ${QUBIT} ${MODE};
-	@./fusion_ori ./circuit/${TEST} ./tmp/ori_${TEST} 3 ${QUBIT} ${MODE};
-	@(git --no-pager diff --no-index --color-words ./tmp/${TEST} ./tmp/ori_${TEST} && echo "\npassed!") || echo "\nfailed!"
+# check: fusion fusion_ori
+# 	@./fusion ./circuit/${TEST} ./tmp/${TEST} 3 ${QUBIT} ${MODE};
+# 	@./fusion_ori ./circuit/${TEST} ./tmp/ori_${TEST} 3 ${QUBIT} ${MODE};
+# 	@(git --no-pager diff --no-index --color-words ./tmp/${TEST} ./tmp/ori_${TEST} && echo "\npassed!") || echo "\nfailed!"
 
 clean:
-	rm fusion tmp/*.txt
+	rm fusion
